language: node_js
sudo: false
dist: trusty
node_js:
  - "7"

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - npm install -g @angular/cli

install:
  - npm install

cache:
  directories:
    - node_modules

jobs:
  include:
    - script: "npm run test"
    - script: "npm run build --prod"
    - stage: GitHub Release
      script: echo "Deploying to GitHub ..."
    - bash ./.travis-deploy.sh

#      deploy:
#        provider: pages
#        skip_cleanup: true
#        github_token: $GITHUB_TOKEN
#        on:
#          branch: master
